# This file was generated by GoReleaser. DO NOT EDIT.
cask "ldap-password-change" do
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_darwin_amd64.tar.gz"
      sha256 "d02ea11d42a1186b851afec296f8c5263b544cc7ebf2963e23daecdb6320a2a9"
    end
    on_arm do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_darwin_arm64.tar.gz"
      sha256 "97736b32ba47724e50eb3c70ea49c782f735d21f0fcc7977b55d5881d595c702"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_linux_amd64.tar.gz"
      sha256 "090b3bded047c5f4130083f6f8e6a2d5cfc2b64031376ce9cf3d8670d618043c"
    end
    on_arm do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_linux_arm64.tar.gz"
      sha256 "c800c43e504cf89767187ed379bd604faf2cdb42d5325477066d8a5cdac6b425"
    end
  end

  name "ldap-password-change"
  desc "Tiny Terraform coach"
  homepage "https://marcel2603.github.io/ldap-password-change"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ldap-password-change"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ldap-password-change"]
    end
  end

  # No zap stanza required

end
