# This file was generated by GoReleaser. DO NOT EDIT.
cask "ldap-password-change" do
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_darwin_amd64.tar.gz"
      sha256 "1add178095a391421fada544b6917e38973fc99093b2d7df4ad0bf3e098512b2"
    end
    on_arm do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_darwin_arm64.tar.gz"
      sha256 "d29e59053c11e55f85a816944306cea059528724d55c0ada2847d9d8fed30aed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_linux_amd64.tar.gz"
      sha256 "332fa67b779b5c329b3d17e99446fbc5a4319b4e182102b616fc2e6a0ea3f345"
    end
    on_arm do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_linux_arm64.tar.gz"
      sha256 "a674e68a0f77ae34040cce711e6ece0c98fa4c7ccc2378ef9ae44cf303f29aa9"
    end
  end

  name "ldap-password-change"
  desc "Tiny Terraform coach"
  homepage "https://marcel2603.github.io/ldap-password-change"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ldap-password-change"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ldap-password-change"]
    end
  end

  # No zap stanza required

end
