# This file was generated by GoReleaser. DO NOT EDIT.
cask "ldap-password-change" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_darwin_amd64.tar.gz"
      sha256 "0736f76493f83430381dc9f6afc1174689f5328684c63bffb2f972f24f5e52ab"
    end
    on_arm do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_darwin_arm64.tar.gz"
      sha256 "7e25c9b81315fafd368fe4b16ccdca498bdb013ef75f2fe37b7931852cf4e6d8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_linux_amd64.tar.gz"
      sha256 "6adaefdd3211a6e0fc751c828c2332255db31384c89e4bffea19954684ac5ebd"
    end
    on_arm do
      url "https://github.com/Marcel2603/ldap-password-change/releases/download/v#{version}/ldap-password-change_linux_arm64.tar.gz"
      sha256 "d4fd597e807c1b3f2e8f1036cbcf7b1e694c755a189bff33724ea5422b12cb55"
    end
  end

  name "ldap-password-change"
  desc "Tiny Terraform coach"
  homepage "https://marcel2603.github.io/ldap-password-change"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ldap-password-change"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ldap-password-change"]
    end
  end

  # No zap stanza required

end
