# This file was generated by GoReleaser. DO NOT EDIT.
cask "spikeball-league" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "78258810f19b750f7def6ddf9086dce74b113aaaf547903c9381fc8cec1bc55d"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2fc0aa21e2ca5b8895dcf738627abaf652c92a09c9ffa4728893b6cf367294f3"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "677bb359e2bd26335d43a48e48c516734f5d4a866e78a12175e281c4c7fac453"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "da7f065459905c213665fd1ac2182c928087d61439083b8e6528d24e2168fa18"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_linux_arm64.tar.gz"
    end
  end

  name "spikeball-league"
  desc "Tiny Terraform coach"
  homepage "https://marcel2603.github.io/spikeball-league"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spikeball-league"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spikeball-league"]
    end
  end

  # No zap stanza required

end
