# This file was generated by GoReleaser. DO NOT EDIT.
cask "spikeball-league" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "18d8c8d3f837241410bc50407de25361675c82262d9571376e38ac4959a2407f"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "475fad23572a05a29733ecaad744f9cef648e3e6e9ad16cf6b5e80fa7af77e62"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25003eab509cd6aa75b53ef20aaf3d0c81cc6af6ed115f26b88efce0415bf9ce"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "97afae968d533a4767ab29e58bad042ade1dd9f1625862c5dfc99d22ec01348f"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_linux_arm64.tar.gz"
    end
  end

  name "spikeball-league"
  desc "Tiny Terraform coach"
  homepage "https://marcel2603.github.io/spikeball-league"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spikeball-league"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spikeball-league"]
    end
  end

  # No zap stanza required

end
