# This file was generated by GoReleaser. DO NOT EDIT.
cask "spikeball-league" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "bc6f05f3a424c0e7a40ae54212b49f04a2a6d98e2a46d638da267b70227a97e2"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "45bcd0a83e2d30d73873ede873b7ae4aefa1e4e8bcbdeca68d3a07896ab0fd94"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "17366f05d5379611107a8387b43a6bbd3c111c6a82357da173af488044550d94"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "65f29208fc6e3891a8bb416f3675729365d71e1a73a0e32ad2040e1511090fe8"
      url "https://github.com/Marcel2603/spikeball-league/releases/download/v#{version}/spikeball-league_linux_arm64.tar.gz"
    end
  end

  name "spikeball-league"
  desc "Tiny Terraform coach"
  homepage "https://marcel2603.github.io/spikeball-league"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spikeball-league"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spikeball-league"]
    end
  end

  # No zap stanza required

end
