# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfcoach" do
  name "tfcoach"
  desc "Tiny Terraform coach"
  homepage "https://marcel2603.github.io/tfcoach"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfcoach"

  on_macos do
    on_intel do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_darwin_amd64.tar.gz"
      sha256 "02a7446e0891a014113e8622391740ce5076aeea6862830ea276d331b24df47d"
    end
    on_arm do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_darwin_arm64.tar.gz"
      sha256 "d122dfe056690c50b66525d1b01c940595fec6ab2164ce6caaf222fae4818c04"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_linux_amd64.tar.gz"
      sha256 "4aa2157434749f0adfb38300f6e9f8a30c8e56e62562aeaecf0452dbdfdc40f8"
    end
    on_arm do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_linux_arm64.tar.gz"
      sha256 "03ab2566e2e01a80abdd54a312b1520ca324ccae1dc52e334cc69a5b07bce8f9"
    end
  end

  # No zap stanza required
end
