# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfcoach" do
  name "tfcoach"
  desc "Tiny Terraform coach"
  homepage "https://marcel2603.github.io/tfcoach"
  version "0.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfcoach"

  on_macos do
    on_intel do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_darwin_amd64.tar.gz"
      sha256 "0baf9c5513ad3699e6e396bc7aa5fa6c641f5e903f5fe01f081c371ba2f1a17f"
    end
    on_arm do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_darwin_arm64.tar.gz"
      sha256 "eead6f5d597358b6897035f0088ca891fd5c2ed7dab449fb6bc8885729c74fe5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_linux_amd64.tar.gz"
      sha256 "11f03e18fa09a5013da4c62e7fd40f9ca5632d81db8a1e5f48c8ca1ee1edbf63"
    end
    on_arm do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_linux_arm64.tar.gz"
      sha256 "e35d3fd493dd19986f2d51875dcb6c6cafd8d516135191cac1862768b588bf88"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfcoach"]
    end
  end

  # No zap stanza required
end
