# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfcoach" do
  name "tfcoach"
  desc "Tiny Terraform coach"
  homepage "https://marcel2603.github.io/tfcoach"
  version "0.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfcoach"

  on_macos do
    on_intel do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_darwin_amd64.tar.gz"
      sha256 "3b789a27d5234fdbec76950fe0f6d6131de100a4bc9e281bc9e5a1116c6ceeda"
    end
    on_arm do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_darwin_arm64.tar.gz"
      sha256 "0b92cdd55382c344d027171c4e329d22af4b3cc44b3775102e80dc1ce46bfd03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_linux_amd64.tar.gz"
      sha256 "e8a20a96a8b4209a5abcfdfa0b257b6a4377f5a079fd61e52a2c9e014f88affd"
    end
    on_arm do
      url "https://github.com/Marcel2603/tfcoach/releases/download/v#{version}/tfcoach_linux_arm64.tar.gz"
      sha256 "a3b0074d75d38faa692eaa20172010ce0e634cf492db5c850b738c8829d9be41"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfcoach"]
    end
  end

  # No zap stanza required
end
